https://groups.google.com/forum/?fromgroups#!topic/ns-users/pEAD47UHUH8


# Generated by Topology Generator for Network Simulator (c) Elmurod Talipov
set val(chan)          Channel/WirelessChannel      ;# channel type
set val(prop)          Propagation/TwoRayGround     ;# radio-propagation model
set val(netif)         Phy/WirelessPhy              ;# network interface type
set val(mac)           Mac/802_11                   ;# MAC type
set val(ifq)           Queue/DropTail/PriQueue      ;# interface queue type
set val(ll)            LL                           ;# link layer type
set val(ant)           Antenna/OmniAntenna          ;# antenna model
set val(ifqlen)        500                  ;# max packet in ifq
set val(nn)            4                ;# number of mobilenodes
set val(rp)            WFRP             ;# protocol tye
set val(x)             50               ;# X dimension of topography
set val(y)             50               ;# Y dimension of topography
set val(stop)          500              ;# simulation period 
set val(energymodel)   EnergyModel          ;# Energy Model
set val(initialenergy) 100              ;# value

set ns              [new Simulator]
set tracefd         [open trace-wfrp.tr w]
set namtrace        [open nam-wfrp-802-11.nam w]

$ns trace-all $tracefd
$ns namtrace-all-wireless $namtrace $val(x) $val(y)

set dist(5m)  7.69113e-06
set dist(9m)  2.37381e-06
set dist(10m) 1.92278e-06
set dist(11m) 1.58908e-06
set dist(12m) 1.33527e-06
set dist(13m) 1.13774e-06
set dist(14m) 9.81011e-07
set dist(15m) 8.54570e-07
set dist(16m) 7.51087e-07
set dist(20m) 4.80696e-07
set dist(25m) 3.07645e-07
set dist(30m) 2.13643e-07
set dist(35m) 1.56962e-07
set dist(40m) 1.20174e-07
set dist(50m) 1.11532e-8 
set dist(100m) 2.78831e-9  
set dist(250m) 4.4613e-10
set dist(500m) 9.21756e-11
Phy/WirelessPhy set CSThresh_ $dist(30m)
Phy/WirelessPhy set RXThresh_ $dist(30m)
Phy/WirelessPhy set Pt_ 0.09588e-5
#30m
Phy/WirelessPhy set freq_  2.4e+9
Antenna/OmniAntenna set Gt_ 1.0
Antenna/OmniAntenna set Gr_ 1.0



Agent/WFRP set Pt_ 0.09588e-5
Agent/WFRP set L_ 1.0  
Agent/WFRP set Gr_ 1.0
Agent/WFRP set Gt_ 1.0
Agent/WFRP set lambda_ 0.125


# set up topography object
set topo       [new Topography]
$topo load_flatgrid $val(x) $val(y)

create-god $val(nn)

# configure the nodes
$ns node-config -adhocRouting $val(rp) \
            -llType $val(ll) \
             -macType $val(mac) \
             -ifqType $val(ifq) \
             -ifqLen $val(ifqlen) \
             -antType $val(ant) \
             -propType $val(prop) \
             -phyType $val(netif) \
             -channel [new $val(chan)] \
             -topoInstance $topo \
             -agentTrace ON \
             -routerTrace ON \
             -macTrace  OFF \
             -movementTrace OFF \
             -energyModel $val(energymodel) \
             -initialEnergy $val(initialenergy) \
             -rxPower 35.28e-3 \
             -txPower 0.09588e-5\
         -idlePower 712e-6 \
         -sleepPower 144e-9 

             #-IncomingErrProc MultistateErrorProc \
             #-OutgoingErrProc MultistateErrorProc

for {set i 0} {$i < $val(nn) } { incr i } {
        set mnode_($i) [$ns node]
}


$mnode_(0) set X_  2.0 
$mnode_(0) set Y_  4.0
$mnode_(0) set Z_  0.0

$mnode_(1) set X_  8.0
$mnode_(1) set Y_  6.0
$mnode_(1) set Z_  0.0

$mnode_(2) set X_  1.0
$mnode_(2) set Y_  7.0
$mnode_(2) set Z_  0.0

$mnode_(3) set X_  1.0
$mnode_(3) set Y_  7
$mnode_(3) set Z_  0.0 




$ns at 1.0 "[$mnode_(0) set ragent_] sink"

for {set i 0} {$i < $val(nn)} { incr i } {
    $ns initial_node_pos $mnode_($i) 3
}



# Telling nodes when the simulation ends
for {set i 0} {$i < $val(nn) } { incr i } {
    $ns at $val(stop) "$mnode_($i) reset;"
}

# ending nam and the simulation
$ns at $val(stop) "$ns nam-end-wireless $val(stop)"
$ns at $val(stop) "stop"
$ns at [expr $val(stop) + 0.01] "puts \"end simulation\"; $ns halt"
proc stop {} {
    global ns tracefd namtrace
    $ns flush-trace
    close $tracefd
    close $namtrace
}

$ns run
