Module/UW/MPhy_modem/PSK_WHOI_MM set period_ 0.001
Module/UW/MPhy_modem/PSK_WHOI_MM set setting_ 0
Module/UW/MPhy_modem/PSK_WHOI_MM set stack_ 0
Module/UW/MPhy_modem/PSK_WHOI_MM set ID_ 0
Module/UW/MPhy_modem/PSK_WHOI_MM set TxPower_ 100
Module/UW/MPhy_modem/PSK_WHOI_MM set NoiseSPD_ 0
Module/UW/MPhy_modem/PSK_WHOI_MM set debug_ 0
Module/UW/MPhy_modem/PSK_WHOI_MM set show_ 1
Module/UW/MPhy_modem/PSK_WHOI_MM set modemReadHex_ 0
Module/UW/MPhy_modem/PSK_WHOI_MM set packet_rate_ 0
