Module/UW/MPhy_modem/S2C set period_ 0.001
Module/UW/MPhy_modem/S2C set setting_ 0
Module/UW/MPhy_modem/S2C set stack_ 0
Module/UW/MPhy_modem/S2C set ID_ 0
Module/UW/MPhy_modem/S2C set TxPower_ 100
Module/UW/MPhy_modem/S2C set NoiseSPD_ 0
Module/UW/MPhy_modem/S2C set debug_ 0
Module/UW/MPhy_modem/S2C set show_ 0
Module/UW/MPhy_modem/S2C set modemReadHex_ 1
Module/UW/MPhy_modem/S2C set packet_rate_ 0
