# Generated by Topology Generator for Network Simulator (c) Elmurod Talipov
set val(chan)          Channel/WirelessChannel      ;# channel type
set val(prop)          Propagation/TwoRayGround     ;# radio-propagation model
set val(netif)         Phy/WirelessPhy/802_15_4     ;# network interface type
set val(mac)           Mac/802_15_4                 ;# MAC type
set val(ifq)           Queue/DropTail/PriQueue      ;# interface queue type
set val(ll)            LL                           ;# link layer type
set val(ant)           Antenna/OmniAntenna          ;# antenna model
set val(ifqlen)        3	         	    ;# max packet in ifq
set val(nn)            3			    ;# number of mobilenodes
set val(rp)            protoname			    ;# protocol tye
set val(x)             120			    ;# X dimension of topography
set val(y)             120			    ;# Y dimension of topography
set val(stop)          50			    ;# simulation period 
set val(energymodel)   EnergyModel		    ;# Energy Model
set val(initialenergy) 100			    ;# value

set ns        		[new Simulator]
set nf [open pname2.nam w]
$ns namtrace-all-wireless $nf $val(x) $val(y)
set nd [open pname2.tr w]
$ns trace-all $nd

 proc finish {} {
 global ns nf nd
 $ns flush-trace
 close $nf
 close $nd
 exec nam out.nam
 exit 0
 }

for {set i 0} {$i < $val(nn)} {incr i} {set n($i) [$ns node] }
for {set i 0} {$i < $val(nn)} {incr i} {
$ns duplex-link $n($i) $n([expr ($i+1)%$val(nn)]) 1Mb 10ms DropTail
}

$ns trace-queue $n(1) $n(2) $nd

set udp0 [new Agent/UDP]
$ns attach-agent $n(0) $udp0
set cbr0 [new Application/Traffic/CBR]
$cbr0 set packetSize_ 50
$cbr0 set interval_ 0.005
$cbr0 attach-agent $udp0
set null0 [new Agent/Null]
$ns attach-agent $n(2) $null0
$ns connect $udp0 $null0
$ns at 0.5 "$cbr0 start"
$ns rtmodel-at 1.0 down $n(1) $n(2)
$ns rtmodel-at 2.0 up $n(1) $n(2)
$ns at 1.35 "$cbr0 stop"
$ns at 1.5 "finish"
$ns run
