# Redistribution and use in source and binary forms are permitted
# provided that the above copyright notice and this paragraph are
# duplicated in all such forms and that any documentation, advertising
# materials, and other materials related to such distribution.
# 
# THIS SOFTWARE IS PROVIDED AS IS AND WITHOUT ANY EXPRESS OR IMPLIED
# WARRANTIES, INCLUDING, WITHOUT LIMITATION, THE IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
#
#
# # This file was automaticaly generated by GenSeN
# It express the node's position
#
#
# Number of Nodes	: 32
# Simulation Area	: 60 x 100 
# Deployment Strategy	: Clif
# Seed           	: 762424

$node_(0) set X_ 22.599000 
$node_(0) set Y_ 26.170000 
$node_(1) set X_ 17.541000 
$node_(1) set Y_ 45.635000 
$node_(2) set X_ 31.314000 
$node_(2) set Y_ 31.420000 
$node_(3) set X_ 23.496000 
$node_(3) set Y_ 50.845000 
$node_(4) set X_ 10.205000 
$node_(4) set Y_ 33.723000 
$node_(5) set X_ 21.448000 
$node_(5) set Y_ 39.902000 
$node_(6) set X_ 30.826000 
$node_(6) set Y_ 15.720000 
$node_(7) set X_ 2.218000 
$node_(7) set Y_ 2.812000 
$node_(8) set X_ 12.372000 
$node_(8) set Y_ 65.561000 
$node_(9) set X_ 2.487000 
$node_(9) set Y_ 45.649000 
$node_(10) set X_ 2.596000 
$node_(10) set Y_ 20.830000 
$node_(11) set X_ 21.100000 
$node_(11) set Y_ 16.883000 
$node_(12) set X_ 37.980000 
$node_(12) set Y_ 55.993000 
$node_(13) set X_ 42.870000 
$node_(13) set Y_ 6.027000 
$node_(14) set X_ 57.159000 
$node_(14) set Y_ 66.792000 
$node_(15) set X_ 54.015000 
$node_(15) set Y_ 47.799000 
$node_(16) set X_ 49.834000 
$node_(16) set Y_ 12.916000 
$node_(17) set X_ 57.169000 
$node_(17) set Y_ 31.465000 
$node_(18) set X_ 49.931000 
$node_(18) set Y_ 27.987000 
$node_(19) set X_ 10.477000 
$node_(19) set Y_ 33.836000 
$node_(20) set X_ 23.842000 
$node_(20) set Y_ 33.141000 
$node_(21) set X_ 36.887000 
$node_(21) set Y_ 58.505000 
$node_(22) set X_ 12.240000 
$node_(22) set Y_ 66.067000 
$node_(23) set X_ 20.000000 
$node_(23) set Y_ 16.395000 
$node_(24) set X_ 17.531000 
$node_(24) set Y_ 42.733000 
$node_(25) set X_ 28.386000 
$node_(25) set Y_ 11.653000 
$node_(26) set X_ 33.798000 
$node_(26) set Y_ 65.788000 
$node_(27) set X_ 31.264000 
$node_(27) set Y_ 59.377000 
$node_(28) set X_ 51.879000 
$node_(28) set Y_ 56.773000 
$node_(29) set X_ 30.467000 
$node_(29) set Y_ 83.888000 
$node_(30) set X_ 56.106000 
$node_(30) set Y_ 47.191000 
$node_(31) set X_ 39.872000 
$node_(31) set Y_ 58.777000 




PRINTING FOUNDINGS...
 2 3 2 0
 3 5 1 0
 2 1 5 1
 1 4 2 0
