WOSS/GroupMob3D set xFieldWidth_ 			0.0
WOSS/GroupMob3D set yFieldWidth_ 			0.0
WOSS/GroupMob3D set zFieldWidth_ 			0.0
WOSS/GroupMob3D set alpha_ 				0.5
WOSS/GroupMob3D set speedMean_ 				2.0
WOSS/GroupMob3D set directionMean_ 			0.0
WOSS/GroupMob3D set updateTime_ 			1.0
WOSS/GroupMob3D set debug_ 				0.0
WOSS/GroupMob3D set mtrace_	 			0
WOSS/GroupMob3D set mtrace_of_node_	 		0
WOSS/GroupMob3D set pitchMean_ 				0.02
WOSS/GroupMob3D set zmin_	 			1.0
WOSS/GroupMob3D set speedM_	 			0.02
WOSS/GroupMob3D set speedS_	 			0.005
WOSS/GroupMob3D set eta_	 			0.5
WOSS/GroupMob3D set charge_	 			1.0
WOSS/GroupMob3D set leaderCharge_ 			1.0
WOSS/GroupMob3D set leader_ 				0
WOSS/GroupMob3D set sigmaPitch_ 			0.1
WOSS/GroupMob3D set galpha_ 				-1.0

